[package]
name                 = "bang"
version              = "0.0.1"
authors.workspace    = true
categories           = [ "command-line-interface" ]
description          = "Typed interactive terminal prompts such as select, search, review and text input"
edition.workspace    = true
keywords             = [ "cli", "input", "terminal", "prompts" ]
license.workspace    = true
readme               = "../../README.md"
repository.workspace = true

[dependencies]
bang-core = { path = "../bang-core", version = "=0.0.1" }
bang-terminal = { path = "../bang-terminal", version = "=0.0.1" }
libc = "0.2"
screw = { path = "../screw", version = "=0.0.1" }

[lints]
workspace = true
