[package]
name                 = "bang"
version              = "0.0.1"
authors.workspace    = true
categories           = [ "command-line-interface" ]
description          = "typed interactive terminal prompts"
edition.workspace    = true
keywords             = [ "cli", "input", "terminal", "prompts" ]
license.workspace    = true
readme               = "../../README.md"
repository.workspace = true

[dependencies]
bang-core.workspace  = true
bang-screw.workspace = true

[lints]
workspace = true
