[package]
name                 = "pound-derive"
version              = "0.2.1"
description          = "Derive macros for pound"
keywords             = [ "cli", "args", "derive" ]
categories           = [ "development-tools::procedural-macro-helpers" ]
readme               = "README.md"
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[features]
# forwarded from pound's `help` feature, see pound/Cargo.toml
help = [  ]

[lib]
proc-macro = true

[dependencies]
pound-derive-impl.workspace = true

[dev-dependencies]
pound = { path = "../pound" }

[lints]
workspace = true
