[formatting]
align_entries       = true
align_comments      = true
array_auto_collapse = true
column_width        = 100
compact_arrays      = false
indent_tables       = false
reorder_keys        = false
