[package]
name                   = "climax"
version                = "0.1.0"
authors.workspace      = true
categories             = [ "command-line-interface", "command-line-utilities" ]
description            = "Batteries-included CLI crate tying together argument parsing, terminal rendering, and prompts"
edition.workspace      = true
keywords               = [ "cli", "terminal", "prompts", "args", "tui" ]
license.workspace      = true
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true

[features]
anyhow      = [ "dep:anyhow" ]
default     = [ "derive", "interactive", "parse", "render", "structured" ]
derive      = [ "parse", "dep:climax-derive" ]
interactive = [ "dep:bang", "dep:unicode-segmentation" ]
parse       = [ "dep:pound" ]
render      = [ "dep:screw" ]
structured  = [ "dep:serde", "dep:serde_json" ]

[[example]]
name              = "prompt"
required-features = [ "interactive", "structured" ]

[[example]]
name              = "status"
required-features = [ "render" ]

[dependencies]
anyhow = { workspace = true, optional = true }
bang = { workspace = true, optional = true }
climax-derive = { workspace = true, optional = true }
pound = { workspace = true, optional = true, features = [
	"std",
	"help",
] }
screw = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = [ "derive" ] }
serde_json = { workspace = true, optional = true }
unicode-segmentation = { workspace = true, optional = true }

[dev-dependencies]
libc.workspace = true
toml.workspace = true

[lints]
workspace = true
