[package]
name              = "fixture-climax-with-components"
version           = "0.0.0"
edition.workspace = true
publish           = false

[dependencies]
bang.workspace  = true
climax          = { path = "../../../crates/climax" }
pound           = { workspace = true, features = [ "derive", "std" ] }
screw.workspace = true
