[package]
name                 = "bang-cli"
version              = "0.0.1"
authors.workspace    = true
categories           = [ "command-line-interface" ]
description          = "cli for bang widgets"
edition.workspace    = true
keywords             = [ "cli", "input", "terminal", "widgets" ]
license.workspace    = true
readme               = "../../README.md"
repository.workspace = true

[dependencies]
bang.workspace          = true
bang-core.workspace     = true
bang-terminal.workspace = true
pound                   = { workspace = true, features = [ "std", "help", "derive" ] }
serde                   = { version = "1", features = [ "derive" ] }
toml                    = "0.8"

[dev-dependencies]
libc = "0.2"

[[bin]]
name = "bang"
path = "src/main.rs"

[lints]
workspace = true
