[package]
name                 = "bang-screw-pty"
version              = "0.0.1"
authors.workspace    = true
categories           = [ "command-line-interface" ]
description          = "PTY overlay runtime for bang widgets rendered with screw"
edition.workspace    = true
keywords             = [ "cli", "input", "terminal", "pty", "renderer" ]
license.workspace    = true
readme               = "README.md"
repository.workspace = true

[dependencies]
bang-core.workspace     = true
bang-screw.workspace    = true
bang-terminal.workspace = true
screw.workspace         = true
screw-pty.workspace     = true

[lints]
workspace = true
