name: Pins Update

on:
  schedule:
    - cron: "17 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    uses: manic-systems/workflows/.github/workflows/pins-update.yml@cbe0792d849aef0dbad4d2bde960b110761ed905 # v2.1.1
    with:
      client-id: ${{ vars.MANIC_BOT_CLIENT_ID }}
    secrets:
      private-key: ${{ secrets.MANIC_BOT_PRIVATE_KEY }}
